service: public--api

provider:
  name: aws
  runtime: python3.8
  region: ${self:custom.common.awsRegionName}
  logRetentionInDays: ${self:custom.logRetentionInDays.${self:custom.common.stage}}
  # Turn on X-Ray
  tracing:
    lambda: true
    apiGateway: true
  environment:
    GIT_HASH: ${env:GIT_HASH}
    SERVICE_NAME: ${self:service}
    ADMIN_USER_POOL_ID: ${self:custom.adminUserPoolId}
    COMPANY_DATA_BUCKET: ${self:custom.companyDataBucket}
    CUSTOMER_USER_POOL_ID: ${self:custom.customerUserPoolId}
    INSTALLER_CODES_TABLE: ${self:custom.installerCodesTable}
    INSTALLER_QUALIFICATION_TABLE: ${self:custom.installerQualificationTable}
    INSTALLER_SERVICE_AREA_TABLE: ${self:custom.installerServiceAreaTable}
    INSTALLER_USER_POOL_ID: ${self:custom.installerUserPoolId}
    RESERVATIONS_TABLE: ${self:custom.reservationsTable}
    OWNER_ADMIN_GROUP_ID: ${self:custom.ownerAdminGroupId}
    PUBLIC_API_ROOT: ${self:custom.customDomain.domainName}
    STAGE: ${self:custom.common.stage}
    STRIPE_PRIVATE_KEY: ${self:custom.stripePrivateKey}
    USER_DATA_BUCKET: ${self:custom.userDataBucket}

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

package:
  exclude:
    - node_modules/**
    - venv/**
    - tests
    - "*.ipynb"

custom:
  common: ${file(../../../common/custom.yml)}
  alerts: ${file(../../../common/alerts.yml)}
  logRetentionInDays: ${file(../../../common/logRetention.yml)}
  adminUserPoolId: ${cf:auth--core-${self:custom.common.stage}.AdminUserPoolId}
  companyDataBucket: ${cf:installers--core-${self:custom.common.stage}.CompanyDataBucket}
  customerUserPoolId: ${cf:auth--core-${self:custom.common.stage}.CustomerUserPoolId}
  installerUserPoolId: ${cf:auth--core-${self:custom.common.stage}.InstallerUserPoolId}
  installerCodesTable: ${cf:installers--core-${self:custom.common.stage}.InstallerCodesTableName}
  installerCodesTableArn: ${cf:installers--core-${self:custom.common.stage}.InstallerCodesTableArn}
  installerQualificationTable: ${cf:installers--core-${self:custom.common.stage}.InstallerQualificationTableName}
  installerQualificationTableArn: ${cf:installers--core-${self:custom.common.stage}.InstallerQualificationTableArn}
  installerServiceAreaTable: ${cf:installers--core-${self:custom.common.stage}.InstallerServiceAreaTableName}
  installerServiceAreaTableArn: ${cf:installers--core-${self:custom.common.stage}.InstallerServiceAreaTableArn}
  reservationsTable: ${cf:schedule--core-${self:custom.common.stage}.ReservationsTableName}
  reservationsTableArn: ${cf:schedule--core-${self:custom.common.stage}.ReservationsTableArn}
  ownerAdminGroupId: ${cf:auth--core-${self:custom.common.stage}.OwnerAdminGroupId}
  stripePrivateKey: stripe-api-key__${self:custom.common.stage}
  userDataBucket: ${cf:auth--core-${self:custom.common.stage}.UserDataBucket}
  customDomain:
    domainName: ${self:service}--${self:custom.common.stage}.rcdevel.com
    certificateArn: ${self:custom.common.domainCertificateArn}
    basePath: ""
    stage: ${self:custom.common.stage}
    createRoute53Record: true
  pythonRequirements:
    pythonBin: python3
    slim: true
    useStaticCache: false
    dockerizePip: true
    dockerRunCmdExtraArgs: ['--platform', 'linux/amd64', '-v', '${env:PWD}/../../../common/rctools:/var/rctools']

functions:
  app:
    name: ${self:custom.common.appPrefix}
    handler: handler.handler
    role: !GetAtt LambdaAuthApiRole.Arn
    events:
      - http:
          method: any
          path: /
          cors: ${self:custom.common.cors}
      - http:
          method: any
          path: /{proxy+}
          cors: ${self:custom.common.cors}

resources:
  Resources:
    LambdaAuthApiRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.common.appPrefix}--exec
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        PermissionsBoundary: !Sub "${self:custom.common.baselinePermissionBoundaryArn}"
        Policies:
          - PolicyName: ${self:custom.common.appPrefix}--exec-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - ${file(../../../common/resource.policy.yml):statements.logs}
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:DescribeLogStreams
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "log-group:/aws/lambda/auth--*--${opt:stage, self:provider.stage}:log-stream:*"
                - Effect: Allow
                  Action: 
                    - cognito:*Users
                    - cognito-identity:GetUser
                    - cognito-idp:ListUsers
                    - cognito-idp:Admin*
                  Resource: 'arn:aws:cognito-idp:us-east-2:${self:custom.common.accountId}:userpool/us-east-2_*'
                - Effect: Allow
                  Action:
                  - s3:ListBucket
                  - s3:*Object
                  Resource:
                    - 'arn:aws:s3:::${cf:installers--core-${self:custom.common.stage}.CompanyDataBucket}'
                    - 'arn:aws:s3:::${cf:installers--core-${self:custom.common.stage}.CompanyDataBucket}/*'
                    - 'arn:aws:s3:::${cf:auth--core-${self:custom.common.stage}.UserDataBucket}'
                    - 'arn:aws:s3:::${cf:auth--core-${self:custom.common.stage}.UserDataBucket}/*'
                - Effect: Allow
                  Action:
                  - dynamodb:Batch*
                  - dynamodb:*Item
                  - dynamodb:Query
                  - dynamodb:Scan
                  Resource:
                    - '${self:custom.installerCodesTableArn}'
                    - '${self:custom.installerCodesTableArn}/index/*'
                    - '${self:custom.installerQualificationTableArn}'
                    - '${self:custom.installerQualificationTableArn}/index/*'
                    - '${self:custom.installerServiceAreaTableArn}'
                    - '${self:custom.installerServiceAreaTableArn}/index/*'
                    - '${self:custom.reservationsTableArn}'
                    - '${self:custom.reservationsTableArn}/index/*'
