service: customer--api

provider:
  name: aws
  runtime: python3.8
  region: ${self:custom.common.awsRegionName}
  logRetentionInDays: ${self:custom.logRetentionInDays.${self:custom.common.stage}}
  # Turn on X-Ray
  tracing:
    lambda: true
    apiGateway: true
  environment:
    SERVICE_NAME: ${self:service}
    ALERTS_TABLE: ${self:custom.alertsTable}
    CUSTOMER_USER_POOL_ID: ${self:custom.customerUserPoolId}
    INSTALLER_SERVICE_AREA_TABLE: ${self:custom.installerServiceAreaTable}
    INSTALLER_USER_POOL_ID: ${self:custom.installerUserPoolId}
    JOB_SCHEDULE_TABLE: ${self:custom.jobScheduleTable}
    JOBS_TABLE: ${self:custom.jobsTable}
    RESERVATIONS_TABLE: ${self:custom.reservationsTable}
    MESSAGES_TABLE: ${self:custom.messagesTable}
    USER_DATA_BUCKET: ${cf:auth--core-${self:custom.common.stage}.UserDataBucket}
    JOB_NOTE_BUCKET: ${self:custom.jobNoteBucket}
    JOB_PHOTO_BUCKET: ${self:custom.jobPhotoBucket}

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

package:
  exclude:
    - node_modules/**
    - venv/**
    - tests
    - "*.ipynb"

custom:
  common: ${file(../../../common/custom.yml)}
  alerts: ${file(../../../common/alerts.yml)}
  logRetentionInDays: ${file(../../../common/logRetention.yml)}
  alertsTable: ${cf:auth--core-${self:custom.common.stage}.AlertsTableName}
  alertsTableArn: ${cf:auth--core-${self:custom.common.stage}.AlertsTableArn}
  companyDataBucket: ${cf:installers--core-${self:custom.common.stage}.CompanyDataBucket}
  customerUserPoolArn: arn:aws:cognito-idp:${aws:region}:${aws:accountId}:userpool/${cf:auth--core-${self:custom.common.stage}.CustomerUserPoolId}
  customerUserPoolId: ${cf:auth--core-${self:custom.common.stage}.CustomerUserPoolId}
  # installerUserPoolArn: arn:aws:cognito-idp:${aws:region}:${aws:accountId}:userpool/${cf:auth--core-${self:custom.common.stage}.InstallerUserPoolId}
  installerServiceAreaTable: ${cf:installers--core-${self:custom.common.stage}.InstallerServiceAreaTableName}
  installerServiceAreaTableArn: ${cf:installers--core-${self:custom.common.stage}.InstallerServiceAreaTableArn}
  installerUserPoolId: ${cf:auth--core-${self:custom.common.stage}.InstallerUserPoolId}
  jobsTable: ${cf:jobs--core-${self:custom.common.stage}.JobsTableName}
  jobsTableArn: ${cf:jobs--core-${self:custom.common.stage}.JobsTableArn}
  reservationsTable: ${cf:schedule--core-${self:custom.common.stage}.ReservationsTableName}
  reservationsTableArn: ${cf:schedule--core-${self:custom.common.stage}.ReservationsTableArn}
  jobScheduleTable: ${cf:schedule--core-${self:custom.common.stage}.JobScheduleTableName}
  jobScheduleTableArn: ${cf:schedule--core-${self:custom.common.stage}.JobScheduleTableArn}
  jobNoteBucket: ${cf:jobs--core-${self:custom.common.stage}.JobNoteBucket}
  jobPhotoBucket: ${cf:jobs--core-${self:custom.common.stage}.JobPhotoBucket}
  messagesTable: ${cf:auth--core-${self:custom.common.stage}.MessagesTableName}
  messagesTableArn: ${cf:auth--core-${self:custom.common.stage}.MessagesTableArn}
  customDomain:
    domainName: ${self:service}--${self:custom.common.stage}.rcdevel.com
    certificateArn: ${self:custom.common.domainCertificateArn}
    basePath: ""
    stage: ${self:custom.common.stage}
    createRoute53Record: true
  pythonRequirements:
    pythonBin: python3
    slim: true
    useStaticCache: false
    dockerizePip: true
    dockerRunCmdExtraArgs: ['--platform', 'linux/amd64', '-v', '${env:PWD}/../../../common/rctools:/var/rctools']

functions:
  app:
    name: ${self:custom.common.appPrefix}
    handler: handler.handler
    role: !GetAtt LambdaAuthApiRole.Arn
    events: ${file(serverless.${self:custom.common.stage}.yml):events}
    timeout: 25

resources:
  Resources:
    LambdaAuthApiRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.common.appPrefix}--exec
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        PermissionsBoundary: !Sub "${self:custom.common.baselinePermissionBoundaryArn}"
        Policies:
          - PolicyName: ${self:custom.common.appPrefix}--exec-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - ${file(../../../common/resource.policy.yml):statements.logs}
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:DescribeLogStreams
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "log-group:/aws/lambda/auth--*--${opt:stage, self:provider.stage}:log-stream:*"
                - Effect: Allow
                  Action: 
                    - cognito:*Users
                    - cognito-identity:GetUser
                    - cognito-idp:ListUsers
                    - cognito-idp:Admin*User
                    - cognito-idp:Admin*Group
                    - cognito-idp:AdminUpdateUserAttributes
                    - cognito-idp:AdminResetUserPassword
                  Resource: 'arn:aws:cognito-idp:us-east-2:${self:custom.common.accountId}:userpool/us-east-2_*'
                - Effect: Allow
                  Action:
                  - s3:ListBucket
                  - s3:*Object
                  Resource:
                    - 'arn:aws:s3:::${cf:auth--core-${self:custom.common.stage}.UserDataBucket}'
                    - 'arn:aws:s3:::${cf:auth--core-${self:custom.common.stage}.UserDataBucket}/*'
                    - 'arn:aws:s3:::${cf:auth--core-${self:custom.common.stage}.UserDataBucket}'
                    - 'arn:aws:s3:::${cf:auth--core-${self:custom.common.stage}.UserDataBucket}/*'
                    - 'arn:aws:s3:::${cf:jobs--core-${self:custom.common.stage}.JobNoteBucket}'
                    - 'arn:aws:s3:::${cf:jobs--core-${self:custom.common.stage}.JobNoteBucket}/*'
                    - 'arn:aws:s3:::${cf:jobs--core-${self:custom.common.stage}.JobPhotoBucket}'
                    - 'arn:aws:s3:::${cf:jobs--core-${self:custom.common.stage}.JobPhotoBucket}/*'
                - Effect: Allow
                  Action:
                  - dynamodb:Batch*
                  - dynamodb:*Item
                  - dynamodb:Query
                  - dynamodb:Scan
                  Resource:
                    - '${self:custom.alertsTableArn}'
                    - '${self:custom.alertsTableArn}/index/*'
                    - '${self:custom.installerServiceAreaTableArn}'
                    - '${self:custom.installerServiceAreaTableArn}/index/*'
                    - '${self:custom.jobScheduleTableArn}'
                    - '${self:custom.jobScheduleTableArn}/index/*'
                    - '${self:custom.jobsTableArn}'
                    - '${self:custom.jobsTableArn}/index/*'
                    - '${self:custom.messagesTableArn}'
                    - '${self:custom.messagesTableArn}/index/*'
                    - '${self:custom.reservationsTableArn}'
                    - '${self:custom.reservationsTableArn}/index/*'
                    
